# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pale Black
email: pale_black@outlook.com
description: >
 Pale Black is a diversified Death Metal band from Switzerland
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.paleblack.ch" # the base hostname & protocol for your site
facebook-url: "https://www.facebook.com/pages/Pale-Black/878060698885724"
mail-url: "mailto:pale_black@outlook.com"
soundcloud-url: "https://soundcloud.com/pale-black-712434955"
github-url: "https://github.com/PaleBlack/paleblack.github.io"
twitter-url: "https://twitter.com/paleblack_band"

# Build settings
markdown: kramdown

collections:
 -  concerts


sass:
  style: nested
